package com.example.tdd.mapper;

import com.example.tdd.pojo.StudentDO;

public interface StudentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbg.generated Sun Mar 27 11:37:15 CST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbg.generated Sun Mar 27 11:37:15 CST 2022
     */
    int insert(StudentDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbg.generated Sun Mar 27 11:37:15 CST 2022
     */
    int insertSelective(StudentDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbg.generated Sun Mar 27 11:37:15 CST 2022
     */
    StudentDO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbg.generated Sun Mar 27 11:37:15 CST 2022
     */
    int updateByPrimaryKeySelective(StudentDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbg.generated Sun Mar 27 11:37:15 CST 2022
     */
    int updateByPrimaryKey(StudentDO record);
}